### ISSUE TITLE
Allow multiple devices

### ISSUE THREAD

**Issue by joaomruas** [joogps/MQTT-Climate-Sync#1]
Hi there, great project.

Is there any way to have multiple instances inside Home assistant?
(This doesn't work)
```sh
mqtt_climate_sync:
  - topic: x
    climate: x
  - topic: x
    climate: x
  - topic: x
    climate: x
```

**Comment by joaomruas** [comment]
Studied the code but decided the easiest way was just implementing this integration multiple times;
Changing 
DOMAIN = "mqtt_climate_sync" to
DOMAIN = "mqtt_climate_sync_0" , DOMAIN = "mqtt_climate_sync_1" etc

**Comment by joogps** [comment]
Hi! I reformatted parts of the code and added the option of creating multiple configurations with commit aa8b66f

:)

**Comment by joaomruas** [comment]
Thanks!
